export type ClawRuleNode = { readonly kind: "rule"; readonly selector: string; readonly declarations: string };
export type ClawCondition = "refreshSpin" | "reducedMotion" | "filters" | "narrowPanel" | "compact" | "mobile";
export type ClawConditionNode = { readonly kind: "condition"; readonly condition: ClawCondition; readonly children: readonly ClawNode[] };
export type ClawNode = ClawRuleNode | ClawConditionNode;

const rule = (selector: string, declarations: string): ClawRuleNode => ({ kind: "rule", selector, declarations });
const condition = (name: ClawCondition, children: readonly ClawNode[]): ClawConditionNode => ({ kind: "condition", condition: name, children });

export const appRules = [
  rule("*", "box-sizing:border-box"),
  rule("html,\nbody,\n#root", "min-width:0;margin:0;overflow-x:hidden"),
  rule(".linear-shell", "height:100vh;height:100dvh;min-height:0;background:var(--bg);color:var(--text);display:grid;grid-template-rows:{{layout.shellRows}};font-size:14px;min-width:0"),
  rule("button,\ninput,\nselect,\ntextarea", "font:inherit"),
  rule("select", "color-scheme:inherit;min-height:var(--control-height);border:1px solid var(--control-border);border-radius:var(--control-radius);background-color:var(--field);color:var(--text);padding:0 9px;outline:0;cursor:pointer;transition:background-color 120ms ease, border-color 120ms ease, color 120ms ease"),
  rule("select:hover:not(:disabled)", "background-color:var(--control-hover)"),
  rule("select:disabled", "cursor:default;opacity:0.45"),
  rule("select:focus-visible", "border-color:var(--focus-ring);outline:2px solid var(--focus-ring);outline-offset:1px"),
  rule("select option", "background-color:var(--field);color:var(--text)"),
  rule("select option:checked", "background-color:var(--control-active);color:var(--text)"),
  rule("button", "border:1px solid var(--control-border);border-radius:var(--control-radius);background:var(--control);color:var(--text);cursor:pointer;transition:background-color 120ms ease, border-color 120ms ease, color 120ms ease"),
  rule("button:hover:not(:disabled)", "background:var(--control-hover)"),
  rule("button:focus-visible", "outline:2px solid var(--focus-ring);outline-offset:2px"),
  rule("button:disabled", "cursor:default;opacity:0.45"),
  rule(".inline-control", "--inline-control-width:120px;position:relative;width:var(--inline-control-width);height:var(--control-height);display:inline-flex;align-items:center;border:0;border-radius:var(--control-radius);background:transparent;color:var(--text);padding:0;font-size:12px;white-space:nowrap"),
  rule(".inline-select-trigger", "position:relative;width:100%;height:100%;min-width:0;display:grid;grid-template-columns:auto minmax(0, 1fr);align-items:center;gap:var(--space-2);border:1px solid var(--control-border);border-radius:inherit;background:transparent;color:var(--text);padding:0 28px 0 9px;font-size:12px;text-align:left"),
  rule(".inline-select-trigger > span", "color:var(--muted)"),
  rule(".inline-select-trigger > strong", "min-width:0;overflow:hidden;color:var(--text);font-weight:650;text-overflow:ellipsis"),
  rule(".inline-select-trigger::after", "position:absolute;top:50%;right:11px;width:6px;height:6px;border-right:1.5px solid var(--muted);border-bottom:1.5px solid var(--muted);content:\"\";pointer-events:none;transform:translateY(-65%) rotate(45deg)"),
  rule(".inline-select-trigger:focus-visible", "border-color:var(--focus-ring);outline:2px solid var(--focus-ring);outline-offset:1px"),
  rule(".inline-control:has(.inline-select-trigger:disabled)", "cursor:default;opacity:0.45"),
  rule(".inline-control:has(.inline-select-trigger:disabled) > button", "opacity:1"),
  rule(".inline-dropdown-menu", "position:fixed;z-index:200;overflow-y:auto;border:1px solid var(--control-border);border-radius:var(--control-radius);background:var(--surface-raised);box-shadow:var(--menu-shadow);padding:var(--space-1)"),
  rule(".inline-dropdown-menu > button", "width:100%;min-height:30px;display:block;border:0;border-radius:calc(var(--control-radius) - 2px);background:transparent;padding:0 var(--space-2);color:var(--text);font-size:12px;text-align:left"),
  rule(".inline-dropdown-menu > button[aria-selected=\"true\"]", "background:var(--control-active);font-weight:700"),
  rule(".inline-control[data-control=\"status\"]", "--inline-control-width:112px"),
  rule(".inline-control[data-control=\"health\"]", "--inline-control-width:146px"),
  rule(".inline-control[data-control=\"sort\"]", "--inline-control-width:160px"),
  rule(".inline-control[data-control=\"rows\"]", "--inline-control-width:144px"),
  rule(".inline-control[data-control=\"priority\"]", "--inline-control-width:112px"),
  rule(".inline-control[data-control=\"assignee\"]", "--inline-control-width:153px"),
  rule(".inline-control[data-control=\"label\"]", "--inline-control-width:166px"),
  rule(".top-chrome", "background:var(--chrome);border-bottom:1px solid var(--line);display:grid;grid-template-columns:auto minmax(180px, 1fr) auto 36px 36px;align-items:center;gap:var(--space-2);padding:0 var(--space-2)"),
  rule(".top-refresh-pill", "min-height:30px;border:1px solid var(--control-border);border-radius:999px;background:var(--control);color:var(--text);display:inline-flex;align-items:center;gap:var(--icon-gap);padding:0 var(--space-3);font-size:12px;font-weight:650;white-space:nowrap"),
  rule(".top-refresh-pill:hover", "border-color:var(--muted);background:var(--control-hover)"),
  rule(".top-refresh-pill:focus-visible", "outline:2px solid var(--focus-ring);outline-offset:1px"),
  rule(".refresh-spin", "animation:refresh-spin 700ms linear infinite"),
  condition("refreshSpin", [
    rule("to", "transform:rotate(360deg)"),
  ]),
  condition("reducedMotion", [
    rule(".refresh-spin", "animation:none"),
  ]),
  rule(".window-tab", "height:30px;border-radius:8px;background:var(--control-hover);display:flex;align-items:center;gap:var(--icon-gap);padding:0 10px;font-weight:700;max-width:210px;min-width:0"),
  rule(".window-tab span", "min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"),
  rule(".address", "align-self:center;justify-self:center;display:flex;align-items:center;color:var(--nav-title);font-weight:var(--weight-nav-title);font-size:var(--font-nav-title);line-height:1;min-width:0;max-width:100%;overflow:hidden;padding:0 var(--space-2);text-overflow:ellipsis;white-space:nowrap"),
  rule(".toolbar-menu-wrap", "position:relative;width:30px"),
  rule(".toolbar-menu", "position:absolute;z-index:40;top:34px;right:0;width:190px;padding:6px;border:1px solid var(--line2);border-radius:7px;background:var(--panel);box-shadow:var(--menu-shadow)"),
  rule(".toolbar-menu > strong", "display:block;padding:7px 9px;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:0.05em"),
  rule(".toolbar-menu button", "width:100%;min-height:32px;border:0;border-radius:5px;background:transparent;color:var(--text);text-align:left;padding:0 9px"),
  rule(".toolbar-menu button:hover:not(:disabled)", "background:var(--hover)"),
  rule(".toolbar-menu button:disabled", "color:var(--green);opacity:1"),
  rule(".database-menu-row", "display:flex;align-items:center;gap:var(--space-1)"),
  rule(".database-menu-row .database-select", "min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"),
  rule(".database-menu-row .database-delete", "width:32px;flex:0 0 32px;padding:0;color:var(--muted);display:grid;place-items:center"),
  rule(".database-menu-row .database-delete:hover:not(:disabled)", "color:var(--red);background:var(--danger-soft)"),
  rule(".ghost-icon.active,\n.health-check.healthy", "color:var(--green);background:var(--hover)"),
  rule(".health-check.error", "color:var(--red)"),
  rule(".health-check.checking", "color:var(--yellow)"),
  rule(".linear-page", "min-height:0;min-width:0;display:grid;grid-template-rows:42px 44px minmax(0, 1fr);background:var(--bg)"),
  rule(".crumbbar", "height:42px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:var(--icon-gap);padding:0 var(--space-3);background:var(--surface)"),
  rule(".crumbbar button,\n.ghost-icon,\n.crumb-icon,\n.round-icon,\n.stack-icon", "border:0;background:transparent;color:var(--muted)"),
  rule(".crumbbar strong", "font-size:14px"),
  rule(".crumb-icon", "width:16px;height:16px;flex:0 0 16px;display:grid;place-items:center"),
  rule(".crumbbar > button:not(.ghost-icon):not(.crumb-icon)", "min-height:var(--control-height);color:var(--text);padding:0;font-weight:700"),
  rule(".crumb-actions", "margin-left:auto;display:flex;align-items:center;gap:var(--space-2)"),
  rule(".project-shortcut-button", "align-items:center;background:var(--control);border:1px solid var(--control-border);border-radius:999px;color:var(--text);display:inline-flex;font-size:12px;font-weight:700;gap:var(--icon-gap);height:var(--control-height);padding:0 var(--pill-inset)"),
  rule(".project-shortcut-button:hover", "background:var(--hover)"),
  rule(".view-tabs", "height:44px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:var(--space-2);padding:0 var(--space-2);background:var(--surface)"),
  rule(".pill,\n.mode-chip", "min-height:var(--pill-height);border:1px solid transparent;border-radius:999px;background:var(--field);color:var(--muted);padding:0 var(--pill-inset);font-weight:650"),
  rule(".pill.active,\n.mode-chip.active", "background:var(--control-active);color:var(--text)"),
  rule(".stack-icon", "height:28px;width:28px"),
  rule(".view-tools", "margin-left:auto;display:flex;gap:var(--space-2)"),
  rule(".round-icon,\n.ghost-icon", "width:30px;height:30px;border-radius:999px;display:grid;place-items:center"),
  rule(".round-icon", "background:var(--control)"),
  rule(".round-icon.active", "background:var(--control-active);color:var(--text)"),
  rule(".decorative", "cursor:default;pointer-events:none"),
  rule(".round-icon:hover,\n.ghost-icon:hover,\n.project-row:hover,\n.linear-issue-row:hover", "background:var(--hover)"),
  rule(".askbar", "border-top:1px solid var(--line);color:var(--muted);display:flex;align-items:center;justify-content:flex-end;padding:0 16px;background:var(--surface);font-size:12px"),
  rule(".projects-screen", "min-height:0;overflow:auto;padding:4px 0"),
  rule(".project-view-config", "min-width:760px;min-height:48px;border-bottom:1px solid var(--line);background:var(--surface);display:flex;align-items:center;gap:var(--space-3);padding:var(--space-2) var(--space-4)"),
  rule(".project-filter-controls,\n.project-sort-control,\n.project-search,\n.project-form label,\n.project-form-actions", "display:flex;align-items:center;gap:var(--space-2)"),
  rule(".project-filter-controls", "min-width:0;flex:1"),
  rule(".project-search,\n.project-filter-controls > button", "height:var(--control-height)"),
  rule(".project-search", "min-width:190px;border:1px solid var(--control-border);border-radius:var(--control-radius);background:var(--control);color:var(--text);padding:0 9px"),
  rule(".project-search input", "min-width:0;border:0;outline:0;background:transparent;color:var(--text)"),
  rule(".project-filter-controls > button", "display:inline-flex;align-items:center;gap:5px;padding:0 10px"),
  rule(".project-result-count", "margin-left:auto;color:var(--dim);font-size:12px;white-space:nowrap"),
  rule(".projects-table", "width:100%;display:grid;padding:0"),
  rule(".project-row", "width:100%;min-height:48px;display:grid;grid-template-columns:{{layout.projectColumns}};align-items:center;gap:12px;border:0;background:transparent;color:var(--muted);text-align:left;padding:0 12px"),
  rule(".project-head", "min-height:42px;color:var(--dim);font-size:12px;pointer-events:none"),
  rule(".project-name", "display:flex;align-items:center;gap:10px;color:var(--text);font-weight:750;min-width:0"),
  rule(".project-name-head", "color:inherit;font-weight:inherit"),
  rule(".project-name > span:last-child", "min-width:0;display:grid;gap:2px"),
  rule(".project-name strong,\n.project-name small,\n.project-lead,\n.project-target,\n.project-priority", "overflow:hidden;white-space:nowrap;text-overflow:ellipsis"),
  rule(".project-name small", "color:var(--dim);font-size:11px;font-weight:500"),
  rule(".project-priority,\n.project-lead,\n.health-badge", "display:inline-flex;align-items:center;gap:6px"),
  rule(".health-badge", "color:var(--muted);font-size:12px;white-space:nowrap"),
  rule(".health-badge.none", "color:var(--dim)"),
  rule(".health-dot", "width:9px;height:9px;border-radius:999px;background:var(--green);box-shadow:0 0 0 3px color-mix(in srgb, var(--green) 14%, transparent)"),
  rule(".health-badge.at_risk .health-dot", "background:var(--yellow);box-shadow:0 0 0 3px color-mix(in srgb, var(--yellow) 14%, transparent)"),
  rule(".health-badge.off_track .health-dot", "background:var(--red);box-shadow:0 0 0 3px color-mix(in srgb, var(--red) 14%, transparent)"),
  rule(".health-badge.complete .health-dot", "background:var(--blue);box-shadow:0 0 0 3px color-mix(in srgb, var(--blue) 14%, transparent)"),
  rule(".project-empty", "padding:42px 16px"),
  rule(".project-dialog", "width:min(720px, 100%)"),
  rule(".database-dialog", "width:min(520px, calc(100vw - 32px))"),
  rule(".database-dialog > p", "color:var(--muted);line-height:1.5"),
  rule(".database-delete-summary", "display:grid;gap:var(--space-2);margin:var(--space-4) 0;padding:var(--space-3);border:1px solid var(--danger-border);border-radius:var(--control-radius);background:var(--danger-soft)"),
  rule(".database-delete-summary code", "color:var(--muted);overflow-wrap:anywhere"),
  rule(".project-form-actions .danger-action", "border-color:var(--danger-border);background:var(--danger-soft);color:var(--red)"),
  rule(".project-form-actions .danger-action:hover:not(:disabled)", "border-color:var(--red);background:var(--danger-soft)"),
  rule(".database-form,\n.database-form label,\n.new-issue-form,\n.new-issue-form label,\n.new-issue-priority", "display:grid;gap:var(--space-2)"),
  rule(".database-form input,\n.new-issue-form input,\n.new-issue-form textarea", "width:100%;border:1px solid var(--line2);border-radius:var(--control-radius);background:var(--field);color:var(--text);padding:9px 10px;outline:0"),
  rule(".new-issue-form textarea", "resize:vertical"),
  rule(".database-form label,\n.new-issue-form label,\n.new-issue-priority", "color:var(--muted);font-size:12px"),
  rule(".new-issue-dialog", "width:min(560px, 100%)"),
  rule(".new-issue-dialog > p", "margin:0 0 var(--space-4)"),
  rule(".issue-priority-picker", "position:relative;justify-self:start"),
  rule(".priority-picker-pill", "min-height:var(--control-height);display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:0 var(--space-3)"),
  rule(".priority-picker-menu", "position:absolute;z-index:45;top:calc(100% + var(--space-1));left:0;width:150px;padding:6px;border:1px solid var(--line2);border-radius:var(--control-radius);background:var(--surface);box-shadow:var(--menu-shadow)"),
  rule(".priority-picker-menu button", "width:100%;min-height:var(--control-height);border:0;background:transparent;text-align:left;padding:0 var(--space-2)"),
  rule(".project-dialog h2", "margin-top:0"),
  rule(".project-form", "display:grid;grid-template-columns:repeat(2, minmax(0, 1fr));gap:16px"),
  rule(".project-form label", "min-width:0;align-items:stretch;flex-direction:column;gap:6px;color:var(--muted);font-size:12px"),
  rule(".project-form input,\n.project-form textarea,\n.project-form select", "width:100%;border:1px solid var(--line2);border-radius:var(--control-radius);background:var(--field);color:var(--text);padding:9px 10px;outline:0;resize:vertical"),
  rule(".project-form input:focus,\n.project-form textarea:focus,\n.project-form select:focus", "border-color:var(--blue)"),
  rule(".project-form-wide", "grid-column:1 / -1"),
  rule(".project-form-actions", "justify-content:flex-end"),
  rule(".project-form-actions button", "padding:8px 13px"),
  rule(".project-form-actions button[type=\"submit\"]", "background:var(--primary);border-color:var(--primary);color:var(--on-primary)"),
  rule(".project-name,\n.relation,\n.resource-list button span:last-child", "overflow:hidden;white-space:nowrap;text-overflow:ellipsis"),
  rule(".project-icon", "width:20px;height:20px;flex:0 0 20px;display:inline-grid;place-items:center"),
  rule(".dim", "color:var(--dim)"),
  rule(".avatar", "width:18px;height:18px;border-radius:999px;display:inline-grid;place-items:center;background:var(--surface-active);color:var(--text);font-size:10px;font-weight:800"),
  rule(".project-overview-linear", "min-height:0;overflow:auto;padding:64px 48px 40px;max-width:960px"),
  rule(".project-hero h1", "font-size:26px;margin:0 0 8px;letter-spacing:-0.01em"),
  rule(".project-hero p", "color:var(--muted);max-width:760px;font-size:16px;line-height:1.45;margin:0 0 26px"),
  rule(".properties-row,\n.resources-row", "display:grid;grid-template-columns:88px minmax(0, 1fr);gap:18px;margin:18px 0"),
  rule(".properties-row", "grid-template-columns:88px repeat(5, auto);align-items:center;justify-content:start;column-gap:16px"),
  rule(".prop-label", "color:var(--muted);font-weight:650"),
  rule(".prop-item,\n.status-pill,\n.priority", "display:inline-flex;align-items:center;gap:6px;color:var(--text);white-space:nowrap"),
  rule(".resource-list", "display:grid;grid-template-columns:repeat(2, minmax(240px, 1fr));gap:8px 20px;max-width:760px"),
  rule(".resource-list button", "border:0;background:transparent;color:var(--text);display:flex;gap:8px;min-width:0;text-align:left;font-weight:650"),
  rule(".resource-list button:hover", "color:var(--text)"),
  rule(".database-path-control", "width:100%;display:grid;grid-template-columns:minmax(0, 1fr) auto;gap:var(--space-2)"),
  rule(".database-path-control > button", "min-height:var(--control-height);display:inline-flex;align-items:center;gap:var(--icon-gap);padding:0 var(--space-3)"),
  rule(".database-form small", "color:var(--dim);line-height:1.4"),
  rule(".update-box", "margin-top:26px;width:100%;max-width:710px;height:50px;border:1px solid var(--line2);border-radius:8px;background:var(--surface);color:var(--muted);display:flex;align-items:center;justify-content:center;gap:10px"),
  rule(".activity-linear", "min-height:0;overflow:auto;padding:50px 28px"),
  rule(".update-composer", "border:1px solid var(--line2);border-radius:8px;background:var(--surface-raised);min-height:0;padding:var(--space-4);max-width:980px;display:grid;align-content:start;gap:var(--space-4)"),
  rule(".composer-tabs", "display:flex;align-items:center;gap:8px"),
  rule(".composer-tabs span,\n.composer-tabs strong,\n.composer-tabs em", "border-radius:999px;background:var(--pill);padding:4px 9px;color:var(--muted);font-style:normal"),
  rule(".composer-tabs select,\n.workflow-controls select", "border-radius:var(--control-radius)"),
  rule(".update-composer textarea", "min-height:100px;resize:none;border:1px solid var(--control-border);border-radius:var(--control-radius);background:var(--field);color:var(--text);padding:var(--space-3);line-height:1.5;outline:0"),
  rule(".update-composer textarea::placeholder", "color:var(--dim)"),
  rule(".update-composer textarea:focus-visible", "border-color:var(--focus-ring);outline:2px solid var(--focus-ring);outline-offset:1px"),
  rule(".composer-tabs strong", "color:var(--text)"),
  rule(".composer-tabs em", "color:var(--green);background:var(--success-soft)"),
  rule(".update-composer p", "color:var(--dim);font-size:16px"),
  rule(".composer-props", "display:grid;grid-template-columns:90px minmax(0, 1fr);column-gap:var(--space-4);row-gap:var(--space-3);color:var(--muted)"),
  rule(".composer-props strong", "color:var(--text);display:flex;gap:7px;align-items:center"),
  rule(".update-composer button", "justify-self:end;border:0;border-radius:999px;background:var(--control-active);color:var(--text);padding:7px 14px;font-weight:700"),
  rule(".update-composer button:disabled", "cursor:not-allowed;opacity:0.55"),
  rule(".timeline", "margin-top:34px;display:grid;gap:14px;max-width:900px"),
  rule(".timeline-row", "display:flex;align-items:center;gap:10px;color:var(--muted)"),
  rule(".issues-screen", "min-height:0;min-width:0;display:grid;grid-template-rows:auto auto minmax(0, 1fr)"),
  rule(".issue-filter-row", "min-width:0;display:flex;align-items:center;gap:var(--space-2);padding:6px var(--space-3);border-bottom:1px solid var(--line)"),
  rule(".searchbar", "height:var(--control-height);border:1px solid var(--control-border);border-radius:var(--control-radius);background:var(--control);flex:1;display:flex;align-items:center;gap:var(--space-2);padding:0 10px"),
  rule(".searchbar input,\n.comments-box input", "border:0;background:transparent;color:var(--text);outline:0;min-width:0"),
  rule(".searchbar input", "flex:1"),
  rule(".issue-limit-control", "flex:0 0 var(--inline-control-width)"),
  rule(".filter-results", "flex:0 0 auto;color:var(--muted);font-size:12px;white-space:nowrap"),
  rule(".clear-filter-button", "min-height:var(--control-height);display:inline-flex;align-items:center;gap:6px;padding:0 var(--space-2);white-space:nowrap"),
  rule(".mode-row", "min-width:0;display:flex;align-items:center;gap:var(--space-2);padding:6px var(--space-3);border-bottom:1px solid var(--line);flex-wrap:wrap;overflow-x:auto;scrollbar-width:thin"),
  rule(".mode-chip", "flex:0 0 auto;font-size:12px;display:flex;align-items:center;gap:var(--icon-gap)"),
  rule(".mode-chip.danger", "color:var(--red)"),
  rule(".issue-advanced-filters", "display:flex;align-items:center;gap:var(--space-2);margin-left:auto;padding-left:var(--space-1)"),
  condition("filters", [
    rule(".issue-advanced-filters", "flex-basis:100%;margin-left:0"),
  ]),
  rule(".primary-action,\n.comments-box button", "min-height:var(--control-height);display:inline-flex;align-items:center;justify-content:center;gap:6px;border-color:var(--primary);background:var(--primary);color:var(--on-primary);padding:0 var(--space-3);font-weight:750;white-space:nowrap"),
  rule(".create-error", "display:flex;align-items:center;gap:6px;padding:6px 12px;border-bottom:1px solid var(--line);color:var(--red);font-size:12px"),
  rule(".issues-and-detail", "min-height:0;min-width:0;display:grid;grid-template-columns:{{layout.issueSplit}}"),
  rule(".linear-issue-list", "min-height:0;min-width:0;overflow:auto;border-right:1px solid var(--line)"),
  rule(".virtual-issue-space", "position:relative;min-width:100%"),
  rule(".virtual-issue-space > .issue-group", "position:absolute;left:0;right:0"),
  rule(".virtual-issue-space .linear-issue-row", "position:absolute;left:0;right:0"),
  rule(".empty-list", "display:grid;place-items:center;min-height:160px;color:var(--muted)"),
  rule(".group-head", "height:{{dimension.issueGroup}}px;background:var(--surface-raised);border-bottom:1px solid var(--line);display:grid;grid-template-columns:22px 22px auto 1fr;align-items:center;gap:5px;padding:0 10px"),
  rule(".group-head strong", "font-size:15px"),
  rule(".group-head em", "color:var(--muted);font-style:normal;justify-self:start"),
  rule(".group-head button", "border:0;background:transparent;color:var(--muted)"),
  rule(".group-toggle", "width:22px;height:22px;display:grid;place-items:center;border-radius:4px!important;padding:0"),
  rule(".group-toggle:hover", "background:var(--hover);color:var(--text)"),
  rule(".linear-issue-row", "min-height:{{dimension.issueRow}}px;width:100%;border:0;border-bottom:1px solid var(--line);background:transparent;color:var(--text);display:grid;grid-template-columns:{{layout.issueColumns}};align-items:center;gap:6px;text-align:left;padding:0 12px"),
  rule(".linear-issue-row.active", "background:var(--accent-soft)"),
  rule(".linear-issue-row strong", "overflow:hidden;white-space:nowrap;text-overflow:ellipsis"),
  rule(".issue-id,\n.relation,\n.linear-issue-row time", "color:var(--muted)"),
  rule(".issue-detail", "min-height:0;min-width:0;overflow:auto;padding:var(--space-4);background:var(--bg);container-type:inline-size"),
  rule(".issue-detail > *", "min-width:0;max-width:100%"),
  rule(".workflow-controls", "margin:var(--space-4) 0 0;border:1px solid var(--line2);border-radius:var(--control-radius);padding:var(--space-3);width:100%;max-width:100%;display:grid;gap:var(--space-3)"),
  rule(".workflow-controls label", "min-width:0;width:100%;display:grid;grid-template-columns:max-content minmax(0, 1fr);align-items:center;gap:var(--space-3)"),
  rule(".workflow-controls select", "min-width:0;width:100%;max-width:100%"),
  rule(".dependency", "min-width:0;display:flex;justify-content:space-between;align-items:center;gap:var(--space-3)"),
  rule(".dependency.resolved", "color:var(--muted)"),
  rule(".dependency-form", "min-width:0;width:100%;display:grid;grid-template-columns:minmax(130px, 0.8fr) minmax(180px, 1.2fr) auto;gap:var(--space-2)"),
  rule(".dependency-form > *", "min-width:0;max-width:100%"),
  rule(".dependency-form input", "min-width:0;border:1px solid var(--line2);border-radius:5px;background:var(--field);color:var(--text);padding:7px 9px"),
  rule(".issue-dialog-backdrop", "position:fixed;inset:0;z-index:20;background:var(--overlay);display:grid;place-items:center;padding:28px"),
  rule(".issue-dialog", "position:relative;width:min(820px, 100%);max-height:min(820px, calc(100vh - 56px));overflow:auto;border:1px solid var(--line2);border-radius:8px;background:var(--surface);padding:28px;box-shadow:var(--dialog-shadow)"),
  rule(".issue-dialog h2", "font-size:25px;margin:18px 0 12px"),
  rule(".issue-dialog p", "color:var(--muted);line-height:1.6;white-space:pre-wrap"),
  rule(".dialog-close", "position:absolute;top:14px;right:14px;width:30px;height:30px;border:0;border-radius:999px;background:var(--control);color:var(--muted);display:grid;place-items:center"),
  rule(".dialog-close:hover", "background:var(--control-hover);color:var(--text)"),
  rule(".detail-top,\n.detail-pills", "display:flex;gap:8px;align-items:center;color:var(--muted)"),
  rule(".detail-pills", "flex-wrap:wrap"),
  rule(".detail-top", "justify-content:space-between"),
  rule(".issue-detail h2", "font-size:24px;margin:var(--space-4) 0 var(--space-3)"),
  rule(".issue-detail p", "margin:var(--space-4) 0 0;color:var(--text);line-height:1.55;white-space:pre-wrap"),
  rule(".agent-state", "margin-top:var(--space-4);border:1px solid var(--line);border-radius:var(--control-radius);background:var(--surface);padding:var(--space-3);width:100%;max-width:100%;display:grid;gap:var(--space-2)"),
  rule(".agent-state.warning", "border-color:var(--danger-border)"),
  rule(".agent-state-head", "display:flex;align-items:center;justify-content:space-between;gap:8px;color:var(--muted)"),
  rule(".agent-state-head strong", "color:var(--text)"),
  rule(".agent-state-head span", "display:inline-flex;align-items:center;gap:5px;color:var(--red);font-size:12px;font-weight:650"),
  rule(".agent-state p", "margin:0;color:var(--muted);font-size:13px"),
  rule(".agent-state-lines,\n.acceptance-note", "display:grid;gap:6px"),
  rule(".agent-state-lines div,\n.acceptance-note", "min-width:0;display:flex;align-items:center;gap:7px;color:var(--text);font-size:13px"),
  rule(".agent-state-lines span,\n.acceptance-note span", "min-width:0"),
  rule(".agent-state-lines em", "color:var(--muted);font-style:normal;overflow:hidden;white-space:nowrap;text-overflow:ellipsis"),
  rule(".comments-box", "margin-top:var(--space-4);width:100%;max-width:100%;display:grid;gap:var(--space-3)"),
  rule(".comments-box article", "border:1px solid var(--line);border-radius:7px;padding:10px;display:grid;gap:4px"),
  rule(".comments-box form", "min-width:0;width:100%;display:grid;grid-template-columns:minmax(0, 1fr) auto;border:1px solid var(--line2);border-radius:var(--control-radius);padding:var(--space-2)"),
  rule(".comments-box input", "min-width:0;width:100%"),
  condition("narrowPanel", [
    rule(".dependency-form", "grid-template-columns:minmax(0, 1fr)"),
    rule(".workflow-controls label", "align-items:stretch;grid-template-columns:minmax(0, 1fr)"),
    rule(".workflow-controls select,\n  .dependency-form button", "width:100%"),
  ]),
  rule(".empty-detail", "display:grid;place-items:center;color:var(--muted)"),
  rule(".sicon.done", "color:var(--green)"),
  rule(".sicon.started", "color:var(--yellow)"),
  rule(".sicon.blocker", "color:var(--red)"),
  rule(".sicon.paused", "color:var(--blue)"),
  rule(".sicon.canceled", "color:var(--dim)"),
  rule(".sicon.backlog,\n.sicon.todo", "color:var(--muted)"),
  rule(".status-pill", "min-height:var(--pill-height);display:inline-flex;align-items:center;border-radius:999px;background:var(--surface-active);padding:0 var(--pill-inset);gap:var(--icon-gap)"),
  rule(".priority", "min-height:var(--pill-height);display:inline-flex;align-items:center;border-radius:999px;background:var(--surface-active);padding:0 var(--pill-inset);gap:var(--icon-gap)"),
  rule(".priority.p1", "color:var(--red)"),
  rule(".priority.p2", "color:var(--yellow)"),
  rule(".pbars", "display:inline-flex;align-items:end;gap:2px;width:18px;height:15px"),
  rule(".pbars i", "display:block;width:3px;background:var(--muted)"),
  rule(".pbars i:nth-child(1)", "height:6px"),
  rule(".pbars i:nth-child(2)", "height:10px"),
  rule(".pbars i:nth-child(3)", "height:14px"),
  rule(".pbars.p1 i,\n.pbars.p2 i", "background:var(--muted)"),
  condition("compact", [
    rule(".project-row", "grid-template-columns:{{layout.projectColumnsCompact}}"),
    rule(".project-row .project-target,\n  .project-row .status-pill,\n  .project-head span:nth-child(5),\n  .project-head span:nth-child(7)", "display:none"),
    rule(".issues-and-detail", "grid-template-columns:1fr"),
    rule(".issue-detail", "border-top:1px solid var(--line);max-height:44vh"),
    rule(".resource-list,\n  .properties-row", "grid-template-columns:1fr"),
    rule(".project-overview-linear", "padding:36px 24px"),
  ]),
  condition("mobile", [
    rule(".top-chrome", "grid-template-columns:minmax(0, 1fr) 32px 32px 32px"),
    rule(".top-chrome .window-tab", "display:none"),
    rule(".top-refresh-pill", "width:32px;min-height:32px;justify-content:center;padding:0"),
    rule(".top-refresh-pill span", "display:none"),
    rule(".crumbbar,\n  .view-tabs,\n  .mode-row", "overflow-x:auto;scrollbar-width:none"),
    rule(".mode-row", "flex-wrap:nowrap"),
    rule(".issue-advanced-filters", "flex-basis:auto"),
    rule(".crumbbar strong,\n  .crumbbar button:not(.ghost-icon):not(.crumb-icon)", "overflow:hidden;text-overflow:ellipsis;white-space:nowrap"),
    rule(".issue-filter-row", "grid-template-columns:minmax(0, 1fr) 30px 30px"),
    rule(".issue-limit-control", "--inline-control-width:70px"),
    rule(".issue-limit-control span", "display:none"),
    rule(".filter-results", "display:none"),
    rule(".linear-issue-row", "grid-template-columns:{{layout.issueColumnsMobile}};padding:0 8px"),
    rule(".linear-issue-row .relation", "display:none"),
    rule(".project-row", "grid-template-columns:{{layout.projectColumnsMobile}};gap:8px"),
    rule(".project-row .health-badge,\n  .project-row .project-priority,\n  .project-row .project-lead,\n  .project-row .project-target,\n  .project-row .status-pill,\n  .project-head span:nth-child(2),\n  .project-head span:nth-child(3),\n  .project-head span:nth-child(4),\n  .project-head span:nth-child(5),\n  .project-head span:nth-child(7)", "display:none"),
    rule(".project-form", "grid-template-columns:minmax(0, 1fr)"),
    rule(".project-form-wide", "grid-column:1"),
    rule(".properties-row,\n  .resources-row", "grid-template-columns:minmax(0, 1fr)"),
    rule(".resource-list", "grid-template-columns:minmax(0, 1fr)"),
    rule(".issue-dialog-backdrop", "padding:12px"),
    rule(".issue-dialog", "max-height:calc(100vh - 24px);padding:22px 16px"),
  ]),
] as const satisfies readonly ClawNode[];
