import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "lightningcss";
import { appRules, type ClawCondition, type ClawNode } from "../src/styles/app-rules.js";
import { controlAlgebra, design, layoutPrimitives, statusTones } from "../src/styles/design-system.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "src", "App.css");
const cssName = (name: string) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const theme = (values: typeof design.themes.dark | typeof design.themes.light) => Object.entries(values)
  .map(([name, value]) => `--${cssName(name)}:${value}`).join(";");

const aliases = [
  ["panel", "surface"], ["panel2", "surface-raised"], ["panel3", "surface-active"],
  ["line", "border-subtle"], ["line2", "border"], ["hover", "surface-hover"],
  ["pill", "surface-raised"], ["chrome", "surface-raised"], ["field", "surface-raised"],
  ["control", "surface-raised"], ["control-hover", "surface-hover"],
  ["control-active", "surface-active"], ["control-border", "border"],
].map(([name, target]) => `--${name}:var(--${target})`).join(";");

const replacements: Record<string, string | number> = {
  "layout.shellRows": design.layouts.shellRows,
  "layout.projectColumns": design.layouts.projectColumns,
  "layout.projectColumnsCompact": design.layouts.projectColumnsCompact,
  "layout.projectColumnsMobile": design.layouts.projectColumnsMobile,
  "layout.issueSplit": design.layouts.issueSplit,
  "layout.issueColumns": design.layouts.issueColumns,
  "layout.issueColumnsMobile": design.layouts.issueColumnsMobile,
  "dimension.issueGroup": design.dimensions.issueGroup,
  "dimension.issueRow": design.dimensions.issueRow,
};

function tokens() {
  const spaces = design.space.map((value, index) => `--space-${index + 1}:${value}px`).join(";");
  const dimensions = `--control-height:${design.dimensions.control}px;--control-radius:${design.radius}px;--focus-ring:var(--text);--pill-height:${design.dimensions.pill}px;--pill-inset:10px;--icon-gap:${design.space[1]}px`;
  const typography = `--font-family:${design.fontFamily};--font-nav-title:${design.typography.navTitleSize}px;--weight-nav-title:${design.typography.navTitleWeight}`;
  return `:root{color-scheme:dark;${spaces};${dimensions};${typography};${theme(design.themes.dark)};${aliases}}:root[data-theme="light"]{color-scheme:light;${theme(design.themes.light)}}`;
}

const conditions: Record<ClawCondition, string> = {
  refreshSpin: "@keyframes refresh-spin",
  reducedMotion: "@media (prefers-reduced-motion:reduce)",
  filters: `@media (max-width:${design.breakpoints.filters}px)`,
  narrowPanel: "@container (max-width:420px)",
  compact: `@media (max-width:${design.breakpoints.compact}px)`,
  mobile: `@media (max-width:${design.breakpoints.mobile}px)`,
};

function emit(node: ClawNode): string {
  if (node.kind === "rule") return `${node.selector}{${node.declarations}}`;
  return `${conditions[node.condition]}{${node.children.map(emit).join("")}}`;
}

function render() {
  const rulesSource = appRules.map(emit).join("");
  if (/(?:#[\da-f]{3,8}|rgba?\()/i.test(rulesSource)) throw new Error("Raw colors belong in design-system.ts, not app-rules.ts");
  let source = `${tokens()}${rulesSource}`;
  for (const [key, value] of Object.entries(replacements)) source = source.replaceAll(`{{${key}}}`, String(value));
  const unresolved = source.match(/{{[^}]+}}/g);
  if (unresolved) throw new Error(`Unresolved CSS values: ${unresolved.join(", ")}`);
  if (layoutPrimitives.length !== 9 || controlAlgebra.tone.length !== 6 || Object.keys(statusTones).length !== 6) {
    throw new Error("The repo-specific style algebra is incomplete");
  }
  const optimized = transform({ filename: "App.css", code: Buffer.from(source), minify: true });
  return `/* Generated by bun run css:generate. Edit src/styles/*.ts. */\n${new TextDecoder().decode(optimized.code)}\n`;
}

const generated = render();
if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== generated) throw new Error("src/App.css has drifted; run bun run css:generate");
  console.log("generated CSS is current");
} else {
  writeFileSync(outputPath, generated, "utf8");
  console.log("generated src/App.css");
}
